// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://elvlyhzrcavselycsyrv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVsdmx5aHpyY2F2c2VseWNzeXJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3NjYzNDgsImV4cCI6MjA1OTM0MjM0OH0.27og8jN0lkuPcie0agzDF0QrJpjqd4j7y7ptRzbcV3M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);